# Use an underscore so it will break :)
application: _
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail_bounce

env_variables:
  # NOTE you will need to import the corus settings in your own django settings
  # OR perhaps run corus as it's own module?? nawwwwww
  DJANGO_SETTINGS_MODULE: 'corus.settings'

libraries:
- name: django
  version: "1.5"
- name: jinja2
  version: "2.6"

builtins:
- deferred: off

handlers:

# Bounce processing should go to corus
- url: /_ah/bounce
  script: corus.main.app
  # Login admin only because this is an internal google service
  login: admin

# Corus static files handler
- url: /cor/static
  static_dir: corus/static

# Corus home
# Will capture links for tracking pixels, link tracking/redirectors, email tracking pixels, etc
- url: /cor/.*
  script: corus.main.app